### PR TITLE
Pixel 6 transport crash fix

### LINKED ISSUE #682: Transport NullPointerException on Pixel 6
Transport crashes when we install it on Pixel 6 phone.

Image
It seems like we are passing in a null rootDir Path in the TransportPaths constructor.

### PR DESCRIPTION
**Pull request by 03fernanda-palacios**
Weird edge case where no dirs apply to populate with crash reports. We will handle by just not enabling crash reports. Only happens once during installation. Post installation, phone should be able to properly recognize dirs to populate crash reports in.

Only happened on one phone model (pixel 6a)

Fixes #682.

### CODE REVIEW

File: AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/ClientUsbViewModel.kt [hunk 1]
```diff
@@ -93,56 +97,72 @@ class ClientUsbViewModel(
...
-                                                bundleTransmission!!.processReceivedBundle(
-                                                    recencyBlob.senderId,
-                                                    Bundle(targetFile.toFile()))
-                                            }
+                val filesToTransfer = toClientDir.listFiles()
+                if (filesToTransfer.isEmpty()) {
+                    appendMessage("No files found in 'toClient' directory on USB", Color.YELLOW)
+                    return@withContext
+                }
+
```
Comment (breed) [inline AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/ClientUsbViewModel.kt]: this looks like debugging and doesn't express information well or take action. either enhance or remove

File: AndroidApps/android-core/src/main/java/net/discdd/crashreports/LocalReportSender.java [hunk 2]
```diff
@@ -31,17 +31,20 @@ public LocalReportSender(CoreConfiguration coreConfiguration) {
...
+    @Override //might crash reports not be working on transports at all???
     public void send(Context context, CrashReportData errorContent) throws ReportSenderException {
         Path rootDir = context.getApplicationContext().getDataDir().toPath();
         logger.log(INFO, "root directory for acra class " + rootDir);
         Path clientDestDir = rootDir.resolve("to-be-bundled");
         if (clientDestDir.toFile().exists()) {
             logger.log(INFO, "We are writing crash report to client device internal storage");
             rootDir = clientDestDir;
-        } else {
+        } else if (context.getApplicationContext().getExternalFilesDir(null).exists()) {
```
Comment (breed) [inline AndroidApps/android-core/src/main/java/net/discdd/crashreports/LocalReportSender.java]: perhaps we should change this to always write crashreports to the internal director: .getFilesDir(). that would simplify this all and always work.

**Review by breed — CHANGES_REQUESTED** [review]

File: AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/ClientUsbViewModel.kt (hunk 1 above)
Comment (03fernanda-palacios) [reply AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/ClientUsbViewModel.kt]: an unwanted file got tracked (you're right, for debugging purposes). i reverted those commits and pushed my branch. this is a small change to local reports only
