### PR TITLE
Discovery status client fix

### LINKED ISSUE #751: Client home screen has inaccurate discovery status
Discovery status should accurately update users with when p2p discovery has started(denoted by the text "Active")/stopped(denoted by the text "Inactive") BUT is currently only informing when it has started and never stops. See usage of WIFI_P2P_DISCOVERY_STARTED in DDDWifiDirect.

When not connected to wifi, it does report "Inactive" successfully. 

Test using Oppo & RedMi (these are buggiest phones)

### PR DESCRIPTION
**Pull request by matildaVerdejo**
Closes #751 
Technically closes the issue, but still need to add more descriptive inactive scenarios.

### CODE REVIEW

File: AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java [hunk 1]
```diff
@@ -243,8 +246,22 @@ private void discoverPeer(WifiP2pDevice device, String transportId, String encod
 
     AtomicBoolean isReceiverRegistered = new AtomicBoolean(false);
     private void registerBroadcastReceiver() {
+        logger.info("Requesting current Wifi P2p state for receiver registration.");
```
Comment (03fernanda-palacios) [inline AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java]:
```suggestion
```

File: AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java [hunk 2]
```diff
@@ -177,6 +179,7 @@ public void initialize() {
         this.handlerThread = new HandlerThread("WifiP2PHandlerThread");
         this.handlerThread.start();
         this.wifiChannel = wifiP2pManager.initialize(bundleClientService, handlerThread.getLooper(), () -> logger.warning("Framework lost. Ignoring"));
+        logger.info("Has permission: " + hasPermission());
```
Comment (03fernanda-palacios) [inline AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java]:
```suggestion
```
